### ISSUE TITLE
What's the right way to hide visual elements?

### ISSUE THREAD

**Issue by pnachum** [xomaczar/ember-cli-ion-rangeslider#1]
I'm doing this: 

```
{{ember-ion-rangeslider
      type="single"
      min=0
      max=1
      step=0.01
      from=fromVal
      hide_min_max=true
      hide_from_to=true
    }}
```

But I still see those extra visual cues.

![image](https://cloud.githubusercontent.com/assets/2244653/6652652/2e691e34-ca33-11e4-89fb-76bb3a99587f.png)

**Comment by xomaczar** [comment]
No support for this yet. I'll look into it tonight

**Comment by pnachum** [comment]
Thanks!

**Comment by xomaczar** [comment]
@philpee2 Sorry been busy at work, putting final touches on v0.1.0 with full support of all ion.rangeSlider options. Just wanted to keep you in the loop

**Comment by pnachum** [comment]
No worries. Thanks!

**Comment by xomaczar** [comment]
Any other features we are missing or would be nice to have?

**Comment by pnachum** [comment]
Not that I can think of

**Comment by xomaczar** [comment]
K

**Comment by xomaczar** [comment]
@philpee2 I just released a new ember-cli-ion-range-slider with supports all available ionRangeSlilder options, please checkout v.0.1.0
https://www.npmjs.com/package/ember-cli-ion-rangeslider

**Comment by pnachum** [comment]
Thanks!
